spring:
  h2:
    console.enabled: true
  datasource:
    url: jdbc:h2:mem:6c04e574-32d3-43ea-a278-c63d36d0b73b
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
